### PR TITLE
replace uses of deprecated `std::iter::range`

### PR DESCRIPTION
**Pull request by apasel422**

### CODE REVIEW

**Comment by FlashCat** [comment]
r? @Gankro

(I've picked a reviewer for you, use r? to override)

**Comment by Gankro** [comment]
@FlashCat r+

**Comment by FlashCat** [comment]
:pushpin: Commit a4b53d1 has been approved by `Gankro`

**Comment by FlashCat** [comment]
:hourglass: Testing commit a4b53d1 with merge a6577e6...

**Comment by FlashCat** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/contain-rs/linked-list/builds/55177149)

**Pull request merged**
