### PR TITLE
use FlashCat for doc pushes

### PR DESCRIPTION
**Pull request by apasel422**

### CODE REVIEW

**Comment by FlashCat** [comment]
r? @reem

(I've picked a reviewer for you, use r? to override)

**Comment by apasel422** [comment]
@Gankro To get this working properly, can you do what it says here for FlashCat's account: https://help.github.com/articles/keeping-your-email-address-private/#commits-on-github-arent-linking-to-my-account

**Comment by Gankro** [comment]
Sorry which thing in particular do you want done?

**Comment by apasel422** [comment]
> Next, make sure that you have followed the instructions above to use your private email address in your email settings. You need to select this checkbox at least once before GitHub will associate commits using email addresses @users.noreply.github.com with your account.

**Comment by Gankro** [comment]
Done.

**Comment by apasel422** [comment]
Cool. FlashCat is now documenting stuff.

**Pull request merged**
